#!/bin/bash
# Ottimizzazione
echo 'Merhaba!'
echo 'Bu komut dosyası, uluslararası Deepin kullanıcılarının Source.Listi değiştirmesine ve yerel bir Yansı (en yakın ayna) kullanmanın tüm avantajlarından (indirme hızı) yararlanmasına izin verir.'
echo 'Çalıştırdığınızda, orijinal Source.listin bir yedeği betiğin aynı dizinine yerleştirilecektir.'
echo ''
PS3='Seçiminiz:'
options=("Italy" "Austria" "Belgium" "Japan" "Latvia" "Philippines" "Poland" "Türkiye" "Brazil" "Bulgaria" "Canada" "Germany" "Greece" "Indonesia" "Ireland" "Russia" "Singapore" "Slovakia" "South Africa" "Sweden" "United States of America" "United Kingdom" "Vietnam" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Italy")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ba.mirror.garr.it/mirrors/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		echo 'Done! Deepin will now use your local Mirror'
		echo ''
		echo 'If you want to revert back to the original Deepin Mirror, run the following command:'
		echo ''
		echo 'sudo cp backup.sources.list /etc/apt/sources.list'
		echo ''
		;;
        "Austria")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.inode.at/data/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Belgium")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.belnet.be/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Japan")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://www.ftp.ne.jp/Linux/packages/deepin/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Latvia")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://deepin.koyanet.lv/packages/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Philippines")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirrors.dotsrc.org/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Poland")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://piotrkosoft.net/pub/mirrors/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Türkiye")
		echo ''
		echo 'Tamam, şimdi Deepin Linux dağıtımınız için yerel aynayı kullanmaya zorlayacağım.'
		echo ''

cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] https://mirror.dgn.net.tr/deepin apricot main contrib non-free
EOF'
		sudo apt update
		echo ''
		echo 'Orijinal Deepin Aynasına geri dönmek istiyorsanız, aşağıdaki komutu çalıştırın.:'
		echo ''
		echo 'sudo cp backup.sources.list /etc/apt/sources.list'
		echo ''
		echo '1) Çıkış'
		echo ''
		echo '2) Orjinali Getir'
		echo ''
		read -p "Seçiminiz: " Quit , Orjinal
		echo ''
		case $Quit in
			1)
				echo 'Çıkış yapılıyor...'
				sleep 2
				clear
				exit 0
				;;
			*)
				echo 'Geçersiz seçim yaptınız. Lütfen tekrar deneyin.'
				sleep 2
				clear
				exit 0
				;;
		esac
		case $Orijinal in
			1)
				echo 'Geri Getiriliyor...'
				sleep 2
				clear
				sudo cp backup.sources.list /etc/apt/sources.list
				echo ''
				echo 'Geri Getirildi.'
				sleep 2
				clear
				exit 0
				;;
			*)
				echo 'Geçersiz seçim yaptınız. Lütfen tekrar deneyin.'
				sleep 2
				clear
				exit 0
				;;
		esac
		;;
        "Brazil")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://sft.if.usp.br/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Bulgaria")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://deepin.ipacct.com/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Canada")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://deepin.mirror.globo.tech/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Germany")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.fau.de/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Greece")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.cc.uoc.gr/mirrors/linux/deepin/packages/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Indonesia")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://kartolo.sby.datautama.net.id/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Ireland")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.heanet.ie/pub/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Russia")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.yandex.ru/mirrors/deepin/packages/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Singapore")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.0x.sg/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Slovakia")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://tux.rainside.sk/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;

        "South Africa")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://www.ftp.saix.net/linux/distributions/linux-deepin/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Sweden")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.acc.umu.se/mirror/linuxdeepin/packages/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "United States of America")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.jmu.edu/pub/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "United Kingdom")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://www.mirrorservice.org/sites/packages.linuxdeepin.com/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Vietnam")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.freedif.org/Deepin/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
		"Quit")
	    echo 'Bu betiği kullandığınız için teşekkürler XTechnology olarak bizi desteklemeye devam edin.. Deepine Değer!'
		break
		;;
		"Orjinal")
		echo ''
		;;
		*) echo 'Seçim yapmadınız. Lütfen tekrar deneyiniz.';;
	esac
done